- name: Install & Start minikube
  hosts: localhost
  user: ubuntu
  become: no

  tasks:

  - name: 1
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
  
  - name: 2
    shell:
      cmd: chmod +x minikube  

  - name: 3
    shell:
      cmd: sudo mv minikube /usr/local/bin/
      
  - name: 4
    shell:
      cmd: minikube start
