- name: Installs
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  
  - name: 1
    shell:
      cmd: apt-get update && sudo apt-get install -y apt-transport-https
      
  - name: 2
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
         
  - name: 3
    shell:
      cmd: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      
  - name: 4
    shell:
      cmd: apt-get update

  - name: 5
    shell:
      cmd: apt-get install -y kubectl
  
  - name: 6
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 chmod +x minikube  

  - name: 7
    shell:
      cmd: mv minikube /usr/local/bin/
